// Dane szczegółowe dla każdego dnia dziennika podróży.
// Pole "photos" to lista ścieżek do zdjęć z folderu assets/photos/dzien-XX/
// (np. "assets/photos/dzien-02/hoover-dam.jpg") — na razie puste, do uzupełnienia.
const dayData = {
  1: { title:"Wylądowaliśmy w Las Vegas", km:null,
    desc:"Pierwszy dzień w Stanach. Po długim locie transatlantyckim dotarliśmy do Las Vegas, odebraliśmy samochód i zameldowaliśmy się w hotelu przy Strip.",
    list:["Odbiór samochodu wynajętego na całą trasę","Wieczorny spacer po Las Vegas Strip","Pierwszy nocleg w Nevadzie"],
    photos:[] },
  2: { title:"Las Vegas → Flagstaff", km:"ok. 490 km",
    desc:"Wyjechaliśmy z Las Vegas w stronę Arizony. Po drodze zatrzymaliśmy się przy zaporze Hoovera, a później zboczyliśmy do malowniczej Sedony z jej charakterystycznymi czerwonymi skałami.",
    list:["Hoover Dam - zapora na rzece Kolorado","Sedona - czerwone formacje skalne","Nocleg we Flagstaff, Arizona"],
    photos:[] },
  3: { title:"Wielki Kanion → Page", km:"ok. 350 km",
    desc:"Cały dzień poświęciliśmy na Park Narodowy Wielkiego Kanionu - jedną z największych atrakcji przyrodniczych Stanów. Wieczorem dojechaliśmy do Page nad jeziorem Powell.",
    list:["Mather Point - główny punkt widokowy","Fragment szlaku Bright Angel Trail","Desert View Drive wzdłuż krawędzi kanionu","Nocleg w Page, Arizona"],
    photos:[] },
  4: { title:"Kanion Antylopy i Dolina Pomników → Cortez", km:"ok. 430 km",
    desc:"Zobaczyliśmy słynne, rzeźbione przez wodę wąwozy kanionu Antylopy, a później przejechaliśmy jeepami przez ikoniczną Dolinę Pomników, znaną z licznych filmów i westernów.",
    list:["Antelope Canyon - wąwóz skalny","Monument Valley - przejazd jeepem","Goosenecks State Park","Nocleg w Cortez, Kolorado"],
    photos:[] },
  5: { title:"Mesa Verde i Million Dollar Highway → Montrose", km:"ok. 320 km",
    desc:"Zwiedziliśmy Park Narodowy Mesa Verde ze skalnymi osadami dawnych mieszkańców regionu, a następnie przejechaliśmy widokową trasą Million Dollar Highway przez góry Kolorado.",
    list:["Mesa Verde - osady klifowe (UNESCO)","Przejazd przez Silverton i Ouray","Nocleg w rejonie Montrose, Kolorado"],
    photos:[] },
  6: { title:"Black Canyon i Aspen → Denver", km:"ok. 520 km",
    desc:"Rano odwiedziliśmy punkty widokowe Black Canyon of the Gunnison, jednego z najciemniejszych i najwęższych kanionów w USA. Po drodze do Denver zatrzymaliśmy się w eleganckim Aspen.",
    list:["Black Canyon of the Gunnison","Spacer po historycznym Aspen","Nocleg w Denver, Kolorado"],
    photos:[] },
  7: { title:"Denver → Scottsbluff", km:"ok. 440 km",
    desc:"Zwiedziliśmy centrum Denver, a następnie ruszyliśmy na północ w stronę Nebraski, zatrzymując się po drodze w Cheyenne w stanie Wyoming.",
    list:["Zwiedzanie centrum Denver","Postój w Cheyenne, Wyoming","Nocleg w Scottsbluff, Nebraska"],
    photos:[] },
  8: { title:"Chimney Rock i Badlands → Rapid City", km:"ok. 500 km",
    desc:"Po drodze zobaczyliśmy Chimney Rock, charakterystyczną formację skalną liczącą ok. 25 mln lat, a później wjechaliśmy w księżycowy krajobraz Parku Narodowego Badlands.",
    list:["Chimney Rock National Historic Site","Park Narodowy Badlands","Nocleg w Rapid City, Południowa Dakota"],
    photos:[] },
  9: { title:"Mount Rushmore i Devils Tower → Billings", km:"ok. 660 km",
    desc:"Zobaczyliśmy pomnik Mount Rushmore z wykutymi w skale twarzami czterech prezydentów, zajrzeliśmy do starego miasteczka górniczego Deadwood, a na koniec dnia dotarliśmy pod Devils Tower.",
    list:["Mount Rushmore National Memorial","Miasteczko Deadwood","Devils Tower National Monument","Nocleg w Billings, Montana"],
    photos:[] },
  10: { title:"Yellowstone → West Yellowstone", km:"ok. 420 km",
    desc:"Wjechaliśmy do Parku Narodowego Yellowstone od strony północnej i spędziliśmy cały dzień, zwiedzając gorące źródła i baseny geotermalne.",
    list:["Mammoth Hot Springs","Norris Geyser Basin","Dolina Hayden - obserwacja dzikiej zwierzyny","Nocleg w West Yellowstone"],
    photos:[] },
  11: { title:"Yellowstone → Salt Lake City", km:"ok. 620 km",
    desc:"Ostatni dzień w Yellowstone spędziliśmy przy najsłynniejszych atrakcjach parku, po czym ruszyliśmy długą trasą przez Idaho do Salt Lake City.",
    list:["Gejzer Old Faithful","Grand Prismatic Spring","Przejazd przez stan Idaho","Nocleg w Salt Lake City, Utah"],
    photos:[] },
  12: { title:"Salt Lake City", km:null,
    desc:"Ostatni pełny dzień w Stanach spędziliśmy w Salt Lake City, zwiedzając centrum miasta, zanim wieczorem polecieliśmy w stronę domu.",
    list:["Temple Square","Kapitol stanu Utah","Wieczorny lot powrotny"],
    photos:[] },
  13: { title:"Powrót do Warszawy", km:null,
    desc:"Po przesiadce dotarliśmy z powrotem do Warszawy, kończąc trzynastodniową podróż przez amerykański Zachód.",
    list:["Przylot do Warszawy","Koniec podróży"],
    photos:[] }
};

// Przystanki trasy do wyświetlenia na mapie Leaflet.
const stops = [
  { name:"Las Vegas, NV", lat:36.1699, lng:-115.1398 },
  { name:"Flagstaff, AZ", lat:35.1983, lng:-111.6513 },
  { name:"Page, AZ", lat:36.9147, lng:-111.4558 },
  { name:"Cortez, CO", lat:37.3489, lng:-108.5859 },
  { name:"Montrose, CO", lat:38.4783, lng:-107.8762 },
  { name:"Denver, CO", lat:39.7392, lng:-104.9903 },
  { name:"Scottsbluff, NE", lat:41.8666, lng:-103.6672 },
  { name:"Rapid City, SD", lat:44.0805, lng:-103.2310 },
  { name:"Billings, MT", lat:45.7833, lng:-108.5007 },
  { name:"West Yellowstone, MT", lat:44.6621, lng:-111.1044 },
  { name:"Salt Lake City, UT", lat:40.7608, lng:-111.8910 }
];
