// Dane szczegółowe dla każdego dnia dziennika podróży.
// Pole "photos" to lista ścieżek do zdjęć z folderu assets/photos/dzien-XX/
// (np. "assets/photos/dzien-02/hoover-dam.jpg") — na razie puste, do uzupełnienia.
const dayDataPL = {
  1: { title:"Wylądowaliśmy w Las Vegas", km:null,
    desc:"Przylot do Vegas. Zmęczeni, ale miasto czeka. Ogólnie robi duże wrażenie, a Sfera mimo tego, że słońce jeszcze nie zaszło świeci mocno i rozświetla okolicę w przeróżnych barwach. Temperatura, mimo, że jest 22:00 jest prawie niedozniesienia. Gorące łzy napływają mi do oczu, gdy obok przejeżdża samochód. Miasto na pokaz, ale coś w tym jest…",
    list:["Wieczorny spacer po Las Vegas Strip","Sfera (Sphere) rozświetlona wieczorem","Pierwszy nocleg w Nevadzie"] },
  2: { title:"Las Vegas → Flagstaff", km:"ok. 490 km",
    desc:"Od rana również Vegas, ale tym razem na spokojnie. Zwiedzamy hotele i kasyna, a co poniektórym graczom ślina spada na przyciski. Pewnie nawet nie wiedzą, że jest 11:00 rano. Nikt nigdy by takich budynków i rzeczy nigdy nie wybudował, ale TUTAJ to pasuje. Tutaj ma to swoje miejsce i to jest piękne. Po południu dojeżdżamy do Sedony (Arizona). Piękne miasteczko, kolory, światło, roślinność mimo temperatury. Mógłbym tam zamieszkać.",
    list:["Kasyna i hotele przy Las Vegas Strip","Sedona - czerwone skały i wyjątkowe światło","Nocleg we Flagstaff, Arizona"] },
  3: { title:"Wielki Kanion → Page", km:"ok. 350 km",
    desc:"Wielki Kanion Kolorado, który wydaje się rozciągać po horyzont. Wielki…faktycznie jest Grand, Big, Huge, Preposterous. Niesamowity. Z kolei po południu odwiedzamy zwykłą bezpłatną atrakcję przy drodze - Horseshoe Bend. Gigantyczne zakole rzeki Kolorado. Ameryka jest Wielka (dosłownie i w przenośni).",
    list:["Grand Canyon National Park","Horseshoe Bend","Nocleg w Page, Arizona"] },
  4: { title:"Kanion Antylopy i Dolina Pomników → Cortez", km:"ok. 430 km",
    desc:"Raz w lewo, raz w prawo i tak w kółko. W dodatku wysokie na ponad 30 metrów. Kolejny kanion, tym razy Antylopy. Wczoraj i dziś dowiedzieliśmy się jakie rzeczy potrafi robić woda. Dodatkowo spotkanie z ludnością lokalną Diné (Navajo). Klimatyczne miejsce. Potem przejazd i zwiedzanie jeepami Doliny Pomników. A więc to tak wygląda prawdziwy dziki zachód. Niesamowite miejsce.",
    list:["Antelope Canyon i spotkanie ze społecznością Navajo (Diné)","Monument Valley - przejazd jeepem","Nocleg w Cortez, Kolorado"] },
  5: { title:"Mesa Verde i Million Dollar Highway → Montrose", km:"ok. 320 km",
    desc:"Dziś od rana Park Narodowy Mesa Verde. Nawet o tym nigdy nie słyszałem… Później przejazd wysoko, wysoko na około przez Pasmo Gór San Juan i stop w miejscowości otoczonej górami Silverton. Klimatyczne miejsce z klimatem rodem z Westernu, a następnie Ouray, położonego pomiędzy stromymi klifami. Oba ciekawe i urokliwe, małe miasteczka.",
    list:["Mesa Verde National Park","Silverton - miasteczko w górach San Juan","Ouray - miasteczko między klifami","Nocleg w rejonie Montrose, Kolorado"] },
  6: { title:"Black Canyon i Aspen → Denver", km:"ok. 520 km",
    desc:"Od rana stromy, głęboki i niebezpieczny Park Narodowy Black Canyon of the Gunnison. Chyba jedyny na trasie, który faktycznie wydał się dość nieprzyjazny i kompletnie dziki. Widoki i przestrzenie są ogromne, a Painted Wall zapiera dech w piersi. Potem przejazd do Aspen, czyli znanego kurortu narciarskiego, gdzie liczba prywatnych odrzutowców na lotnisku znacznie przewyższała liczbę samolotów pasażerskich. Nigdy też nie widziałem w jednym miejscu tylu ludzi z tak białymi zębami. Ciekawe, o co z tym chodzi…",
    list:["Black Canyon of the Gunnison - punkt widokowy Painted Wall","Aspen - luksusowy kurort narciarski","Nocleg w Denver, Kolorado"] },
  7: { title:"Denver → Scottsbluff", km:"ok. 440 km",
    desc:"Denver nie zachwyciło nas jakoś szczególnie, choć samo położenie miasta jest bardzo ciekawe. Liczyłem na spotkanie jakiegoś zawodnika z Denver Nuggets…no może innym razem. Jeszcze tego samego dnia dojeżdżamy do Wyoming, a konkretnie do Cheyenne, a czas jakby nagle zwolnił.",
    list:["Zwiedzanie Denver","Cheyenne, Wyoming","Nocleg w Scottsbluff, Nebraska"] },
  8: { title:"Chimney Rock i Badlands → Rapid City", km:"ok. 500 km",
    desc:"Rano przejazd do Chimney Rock już w stanie Nebraska, gdzie wielki kamień góruje nad horyzontem. Byłem zachwycony ciszą i spokojem. Cały stan wydawał się bardzo spokojny, wręcz uśpiony. Ciszę zakłócały jedynie gryzące komary. Po cichym i spokojnym spacerze w pobliżu góry udajemy się do Południowej Dakoty, gdzie naszym celem jest Park Narodowy Badlands. Ciężko opisać to miejsce, bo same wysokości skał nie są szczególnie duże, ale to kolory i formy sprawiają, że to miejsce jest tak dzikie i odmienne. Dodatkowym smaczkiem i jest ogromna liczba motocyklistów, która przemieszcza się po parku. Pamiętam jak patrząc na jednym z punktów widokowych przejeżdżała grupa motocyklistów słuchając na głośnikach utworu: R.E.M. - Losing My Religion. Świetny moment.",
    list:["Chimney Rock National Historic Site","Badlands National Park","Nocleg w Rapid City, Południowa Dakota"] },
  9: { title:"Mount Rushmore i Devils Tower → Billings", km:"ok. 660 km",
    desc:"Dziś od rana Południowa Dakota, czyli Góra Rushmore. Mimo, iż myślałem, że twarze prezydentów będą znacznie większe robi to ogromne wrażenie. Dokładność, z jaką twarze są wykute w litej skale, w dodatku tak dawno temu, jest imponujące. Idziemy również na spacer wśród drzew, dzięki czemu zbliżamy się stopniowo do czterech twarzy, które co chwilę wyłaniają się wśród drzew. Świetna atrakcja. Stamtąd jedziemy do miasteczka Deadwood, które zrobiło na mnie wielki wrażenie. Raz, że gdyby nie asfaltowa ulica, reklamy i neony to wyglądałaby jak wyjęta z dawnego dzikiego zachodu, to dwa, było tam po prostu pełno, ale to pełno motocykli i motocyklistów. Tak wystrojonych ludzi i maszyn jeszcze nie widziałem. Tego samego dnia jedziemy jeszcze do miejsca, na które bardzo czekałem, czyli Devils Tower. To ogromna formacja skalna, która znacząco wystaje ponad otaczające tereny. Po tym udajemy się już do Billings w Montanie na nocleg.",
    list:["Mount Rushmore National Memorial","Deadwood - historyczne miasteczko","Devils Tower National Monument","Nocleg w Billings, Montana"] },
  10: { title:"Yellowstone → West Yellowstone", km:"ok. 420 km",
    desc:"Rano jemy tak pyszne śniadanie w pobliskiej śniadaniowni, że zasługuje na wzmiankę tutaj. Tost francuski, jajecznica, syrop klonowy i czipsy z bekonu. Pycha! A po śniadaniu…Park Narodowy Yellowstone! Dzisiaj między innymi: Mammoth Hot Springs, czyli gorące źródła, Norris Geyser Basin, dolina Haydena, czy widok na dolinę rzeki Yellowstone. Emocji dodają również co chwilę pojawiające się bizony, które kompletnie nie zwracają uwagi na samochody i turystów. Wszystkie miejsca są niesamowite i dają poczucie tego, jak małym i bezbronnym się jest względem tak dzikiej przyrody. Wieczorem będąc już w West Yellowstone udajemy się jeszcze na steka i kupujemy pamiątki.",
    list:["Mammoth Hot Springs","Norris Geyser Basin","Dolina Hayden - bizony przy drodze","Nocleg w West Yellowstone"] },
  11: { title:"Yellowstone → Salt Lake City", km:"ok. 620 km",
    desc:"Od rana kontynuujemy zwiedzanie Yellowstone. Dziś: gejzer Old Faithful, gorące źródła Morning Glory Pool i największe gorące źródła w USA – Grand Prismatic Spring. Piękne miejsca, osadzone w pięknej przyrodzie. Po południu wyruszamy w stronę ostatniego miasta na trasie i przejeżdżamy przez stan Idaho, który wydaje się kompletnie pusty, piękny, ale kompletnie opuszczony. Po prostu ogromne przestrzenie przeznaczone na tereny rolnicze. Zanim dotrzemy na miejsce zaraz po wyjeździe z parku Yellowstone wjeżdżamy do Parku Narodowego Grand Teton, który zachywyca wielkimi górami i równie piękną i dziką przyrodą. Dalej zatrzymujemy się w urokliwym miasteczku Jackson Hole, gdzie jemy obiad i przechadzamy się uliczkami.",
    list:["Old Faithful","Morning Glory Pool","Grand Prismatic Spring","Park Narodowy Grand Teton","Jackson Hole","Przejazd przez stan Idaho","Nocleg w Salt Lake City, Utah"] },
  12: { title:"Salt Lake City i powrót do Polski", km:null,
    desc:"Powrót. Choć od rana zwiedzamy Salt Lake City. Bardzo ładne miasto, podobało nam się tam. Kultura mormońska również nas zaciekawiła. Największą ciekawostką był dla nas jednak rozmiar samego jeziora, od którego z resztą miasto wzięło nazwę. Jest ono po prostu gigantyczne. Po południu transfer na lotnisko i lot do Amsterdamu. Wszystko szło gładko, aż do boardingu na samolot do Warszawy. Lot został odwołany, a my zmęczeni dotychczasową podróżą musieliśmy nocować w hotelu i lecieć do Warszawy dopiero następnego dnia o 7:00 rano.",
    list:["Salt Lake City - centrum i kultura mormońska","Wielkie Jezioro Słone","Lot Salt Lake City → Amsterdam","Odwołany lot do Warszawy - nocleg w hotelu","Powrót do Warszawy następnego dnia rano"] }
};

// Angielska wersja dziennika podróży (odpowiednik dayDataPL).
const dayDataEN = {
  1: { title:"We landed in Las Vegas", km:null,
    desc:"Tired after the long flight, but the city makes an impression right away. The Sphere glows in every color even before sunset. At 10 pm the heat is almost unbearable. A city built for show — but there's something to it…",
    list:["Picked up the car for the whole road trip","Evening walk along the Las Vegas Strip","The Sphere lit up at night","First night in Nevada"] },
  2: { title:"Las Vegas → Flagstaff", km:"approx. 490 km",
    desc:"In the morning we explored Las Vegas at a slower pace — casinos and hotels, where some gamblers seem not to notice it's only 11 am. Nowhere else would anyone build places like this, but here it fits, and it's beautiful. In the afternoon we reached Sedona, Arizona — a charming town, full of color and light despite the heat. I could live there.",
    list:["Casinos and hotels along the Las Vegas Strip","Sedona - red rocks and unique light","Overnight in Flagstaff, Arizona"] },
  3: { title:"Grand Canyon → Page", km:"approx. 350 km",
    desc:"The Grand Canyon seems to stretch to the horizon — truly Grand, Big, Huge. In the afternoon we stopped at a free roadside attraction, Horseshoe Bend — a massive bend in the Colorado River. America is Great, literally and figuratively.",
    list:["Grand Canyon National Park","Horseshoe Bend","Overnight in Page, Arizona"] },
  4: { title:"Antelope Canyon and Monument Valley → Cortez", km:"approx. 430 km",
    desc:"Antelope Canyon - narrow, over 30 meters deep, winding left and right. Two days in a row we saw what water can carve out of rock. We also met members of the local Diné (Navajo) community — a very atmospheric place. Later we explored Monument Valley by jeep. So this is what the real Wild West looks like.",
    list:["Antelope Canyon and meeting the Navajo (Diné) community","Monument Valley - jeep tour","Overnight in Cortez, Colorado"] },
  5: { title:"Mesa Verde and the Million Dollar Highway → Montrose", km:"approx. 320 km",
    desc:"Mesa Verde National Park, which I'd never even heard of before. Later, a long, scenic drive through the San Juan Mountains and a stop in Silverton, a mountain town with real Western vibes. Then Ouray, tucked between steep cliffs. Both charming little towns.",
    list:["Mesa Verde National Park","Silverton - a town in the San Juan Mountains","Ouray - a town between the cliffs","Overnight near Montrose, Colorado"] },
  6: { title:"Black Canyon and Aspen → Denver", km:"approx. 520 km",
    desc:"Black Canyon of the Gunnison — steep, deep, and dangerous. Probably the wildest and most unwelcoming spot on the whole trip. The Painted Wall is breathtaking. Afterward we drove to Aspen, the famous ski resort, where the airport had more private jets than passenger planes. I've also never seen so many people with such white teeth in one place. Wonder what that's about…",
    list:["Black Canyon of the Gunnison - Painted Wall overlook","Aspen - luxury ski resort","Overnight in Denver, Colorado"] },
  7: { title:"Denver → Scottsbluff", km:"approx. 440 km",
    desc:"Denver didn't blow us away, though the city's setting is interesting. That same day we reached Cheyenne, Wyoming, where time seemed to suddenly slow down.",
    list:["Sightseeing in Denver","Cheyenne, Wyoming","Overnight in Scottsbluff, Nebraska"] },
  8: { title:"Chimney Rock and Badlands → Rapid City", km:"approx. 500 km",
    desc:"In the morning we reached Chimney Rock in Nebraska, where a tall rock spire looms over the horizon — silence and calm, broken only by mosquitoes. Later, Badlands National Park in South Dakota — the rock formations aren't very tall, but the colors and shapes make this place feel wild and otherworldly. A nice touch: a huge number of motorcyclists riding through the park. I remember watching a group ride past one of the overlooks with R.E.M.'s 'Losing My Religion' playing from a speaker. A great moment.",
    list:["Chimney Rock National Historic Site","Badlands National Park","Overnight in Rapid City, South Dakota"] },
  9: { title:"Mount Rushmore and Devils Tower → Billings", km:"approx. 660 km",
    desc:"Mount Rushmore is impressive - the precision with which the presidents' faces were carved into solid rock, so long ago, is remarkable. Walking a forest trail, the faces gradually appear between the trees. Then the town of Deadwood - without the paved road, ads and neon signs, it could pass for the real Wild West, and it was absolutely packed with motorcyclists. I've never seen so many dressed-up riders and bikes in one place. At the end of the day we reached Devils Tower - a massive rock formation I'd been looking forward to for a long time.",
    list:["Mount Rushmore National Memorial","Deadwood - historic town","Devils Tower National Monument","Overnight in Billings, Montana"] },
  10: { title:"Yellowstone → West Yellowstone", km:"approx. 420 km",
    desc:"We started the day with a breakfast so good it deserves a mention here - French toast, scrambled eggs, maple syrup, and bacon chips. Delicious! Then, Yellowstone National Park all day: Mammoth Hot Springs, Norris Geyser Basin, Hayden Valley, and views over the Yellowstone River valley. Bison kept appearing right by the road, completely ignoring the cars and tourists. Every single place felt incredible and made us feel how small and defenseless you are against nature this wild.",
    list:["Mammoth Hot Springs","Norris Geyser Basin","Hayden Valley - bison by the road","Overnight in West Yellowstone"] },
  11: { title:"Yellowstone → Salt Lake City", km:"approx. 620 km",
    desc:"Second day in Yellowstone: the Old Faithful geyser, Morning Glory Pool, and the largest hot spring in the US - Grand Prismatic Spring. In the afternoon, a long drive through Idaho - completely empty, beautiful, but almost abandoned-feeling, just vast stretches of farmland. Before reaching our destination, right after leaving Yellowstone we enter Grand Teton National Park, which amazes with its towering mountains and equally beautiful, wild nature. Further on we stop in the charming town of Jackson Hole, where we have lunch and wander its streets.",
    list:["Old Faithful","Morning Glory Pool","Grand Prismatic Spring","Grand Teton National Park","Jackson Hole","Driving through Idaho","Overnight in Salt Lake City, Utah"] },
  12: { title:"Salt Lake City and the flight home", km:null,
    desc:"We started the last day exploring Salt Lake City - a really nice city, and Mormon culture was fascinating to us. What impressed us most, though, was the sheer size of the Great Salt Lake, which gave the city its name - it's simply enormous. In the afternoon we transferred to the airport and flew to Amsterdam. Everything went smoothly until boarding for Warsaw - that flight got cancelled, so exhausted from the whole trip, we had to spend the night in a hotel and fly to Warsaw the next morning at 7 am.",
    list:["Salt Lake City - downtown and Mormon culture","The Great Salt Lake","Flight Salt Lake City → Amsterdam","Cancelled flight to Warsaw - overnight hotel stay","Flight home to Warsaw the next morning"] }
};

// Statyczne teksty interfejsu (nagłówki, etykiety) w obu językach.
const uiText = {
  pl: {
    heroEyebrow: "Lipiec–Sierpień 2026",
    heroSubtitle: "Szlakiem parków narodowych Zachodu",
    statDays: "Dni w trasie",
    statStates: "Stanów",
    statParks: "Parków i pomników",
    statKm: "Kilometrów",
    routeEyebrow: "Trasa",
    routeTitle: "Od Las Vegas do Salt Lake City",
    routeDesc: "Jedenaście noclegów, dziewięć stanów, jedna wielka pętla przez Zachód.",
    mapEyebrow: "Na żywo",
    mapTitle: "Mapa trasy",
    mapDesc: "Ta sama pętla, tym razem na prawdziwej mapie — kliknij pinezkę, żeby zobaczyć nazwę przystanku.",
    parksEyebrow: "Najważniejsze przystanki",
    parksTitle: "Parki i pomniki narodowe",
    journalEyebrow: "Dzień po dniu",
    journalTitle: "Dziennik podróży",
    journalDesc: "Kliknij dowolny dzień, żeby zobaczyć więcej szczegółów.",
    dayWord: "Dzień",
    dayHint: "Kliknij, żeby zobaczyć więcej →",
    footerDesc: "Relacja z naszej podróży przez parki narodowe amerykańskiego Zachodu — lipiec–sierpień 2026."
  },
  en: {
    heroEyebrow: "July–August 2026",
    heroSubtitle: "Along the National Parks of the American West",
    statDays: "Days on the road",
    statStates: "States",
    statParks: "Parks & monuments",
    statKm: "Kilometers",
    routeEyebrow: "Route",
    routeTitle: "From Las Vegas to Salt Lake City",
    routeDesc: "Eleven overnight stops, nine states, one big loop through the West.",
    mapEyebrow: "Live map",
    mapTitle: "Route map",
    mapDesc: "The same loop, this time on a real map — click a pin to see the stop's name.",
    parksEyebrow: "Highlights",
    parksTitle: "National Parks & Monuments",
    journalEyebrow: "Day by day",
    journalTitle: "Travel journal",
    journalDesc: "Click any day to see more details.",
    dayWord: "Day",
    dayHint: "Click to see more →",
    footerDesc: "Our trip through the national parks of the American West — July–August 2026."
  }
};

// Przystanki trasy do wyświetlenia na mapie Leaflet.
const stops = [
  { name:"Las Vegas, NV", lat:36.1699, lng:-115.1398 },
  { name:"Flagstaff, AZ", lat:35.1983, lng:-111.6513 },
  { name:"Page, AZ", lat:36.9147, lng:-111.4558 },
  { name:"Cortez, CO", lat:37.3489, lng:-108.5859 },
  { name:"Montrose, CO", lat:38.4783, lng:-107.8762 },
  { name:"Denver, CO", lat:39.7392, lng:-104.9903 },
  { name:"Scottsbluff, NE", lat:41.8666, lng:-103.6672 },
  { name:"Rapid City, SD", lat:44.0805, lng:-103.2310 },
  { name:"Billings, MT", lat:45.7833, lng:-108.5007 },
  { name:"West Yellowstone, MT", lat:44.6621, lng:-111.1044 },
  { name:"Salt Lake City, UT", lat:40.7608, lng:-111.8910 }
];
